import type { CSSProperties } from "react";

/** Co-located styles for AgentPanel. */
export const s = {
  panel: {
    display: "flex",
    flexDirection: "column",
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    minWidth: 0,
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: 16,
    borderBottom: "1px solid var(--border)",
  },
  headerMain: { flex: 1, minWidth: 0 },
  agentName: { fontSize: 15, fontWeight: 700 },
  agentDescription: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginTop: 2,
  },
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
    fontSize: 12,
    color: "var(--text-secondary)",
  },
  stateLabel: { fontSize: 12, fontWeight: 600 },
  stateLabelRunning: { color: "var(--accent)" },
  stateLabelFailed: { color: "var(--crit)" },
  stateLabelDone: { color: "var(--text-secondary)" },
  spinIcon: { animation: "ddspin 1s linear infinite" },
  scoreFallback: {
    fontSize: 13,
    color: "var(--text-muted)",
    width: 44,
    height: 44,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  },
  errorBox: {
    margin: "0 16px 12px",
    padding: 10,
    borderRadius: 8,
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 12.5,
    lineHeight: 1.5,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 16px",
    fontSize: 12,
    color: "var(--text-muted)",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "0 16px 16px",
    overflowY: "auto",
    maxHeight: 640,
  },
  empty: {
    padding: "16px",
    fontSize: 13,
    color: "var(--text-muted)",
  },
} satisfies Record<string, CSSProperties>;
