import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillDrawer. */
export const s = {
  dropzone: (active: boolean): CSSProperties => ({
    display: "grid",
    placeItems: "center",
    gap: 8,
    padding: "32px 20px",
    borderRadius: 10,
    border: "1.5px dashed " + (active ? "var(--accent)" : "var(--border-strong)"),
    background: active ? "var(--accent-bg)" : "var(--bg-elevated)",
    color: "var(--text-secondary)",
    textAlign: "center",
    transition: "border-color .12s ease, background .12s ease",
  }),
  dropTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  dropHint: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  selected: { fontSize: 12.5, color: "var(--text-secondary)", marginTop: 12 } satisfies CSSProperties,
  error: {
    fontSize: 12.5,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    border: "1px solid var(--crit)",
    borderRadius: 7,
    padding: "10px 12px",
    marginTop: 14,
    lineHeight: 1.5,
  } satisfies CSSProperties,

  // ---- preview ----
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "18px 0 8px",
  } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  name: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  description: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5, marginTop: 8 } satisfies CSSProperties,
  warning: {
    display: "flex",
    gap: 10,
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    borderRadius: 7,
    padding: "10px 12px",
    marginTop: 16,
  } satisfies CSSProperties,
  skippedList: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  skippedRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12.5,
    padding: "7px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  skippedPath: { flex: 1, minWidth: 0, overflowWrap: "anywhere" } satisfies CSSProperties,
  bodyBox: {
    maxHeight: 320,
    overflow: "auto",
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 13,
    lineHeight: 1.55,
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
} as const;
