import type { CSSProperties } from "react";
import { RAIL_WIDTH } from "./constants";

/** Co-located styles for ProjectContextView — a fixed rail (folder tree) +
 *  a flexible preview pane, mirroring `app/skills/_components/SkillsView`. */
export const s = {
  layout: { display: "flex", height: "calc(100vh - 52px)", minWidth: 0 } satisfies CSSProperties,
  rail: {
    width: RAIL_WIDTH,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
    minHeight: 0,
  } satisfies CSSProperties,
  railHeader: { padding: "16px 16px 12px" } satisfies CSSProperties,
  railTitleRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 14 } satisfies CSSProperties,
  h1: { fontSize: 16, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  railList: { flex: 1, overflow: "auto", padding: "0 8px 12px" } satisfies CSSProperties,
  railEmpty: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    padding: "8px 8px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  railFooter: {
    padding: "10px 16px",
    borderTop: "1px solid var(--border)",
    fontSize: 11.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,

  folderGroup: { marginBottom: 6 } satisfies CSSProperties,
  folderHeading: {
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    padding: "10px 8px 4px",
  } satisfies CSSProperties,
  docRow: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    minHeight: 28,
    padding: "6px 8px",
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    background: active ? "var(--bg-elevated)" : "transparent",
    color: "var(--text-primary)",
  }),
  docIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  docName: {
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  docTokens: {
    fontSize: 11,
    color: "var(--text-secondary)",
    flexShrink: 0,
  } satisfies CSSProperties,

  detail: { flex: 1, display: "flex", flexDirection: "column", minWidth: 0, minHeight: 0 } satisfies CSSProperties,
  detailHeader: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "16px 24px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  detailFileName: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  modeToggle: { display: "flex", gap: 4 } satisfies CSSProperties,
  modeActive: {
    fontSize: 11.5,
    padding: "3px 10px",
    borderRadius: 6,
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontWeight: 600,
  } satisfies CSSProperties,
  modeDisabled: {
    fontSize: 11.5,
    padding: "3px 10px",
    borderRadius: 6,
    color: "var(--text-muted)",
    cursor: "not-allowed",
  } satisfies CSSProperties,
  usedBy: { marginLeft: "auto", fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  detailBody: { flex: 1, overflow: "auto", padding: "20px 24px" } satisfies CSSProperties,
  detailEmpty: { flex: 1 } satisfies CSSProperties,
  loadingStack: {
    flex: 1,
    padding: 28,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
} as const;
