import type {
  CiExportInput,
  CiExportPreview,
  CiExport,
  CiInstallation,
  CiWorkflowValidation,
  CiFile,
  CiRun,
  CiRefreshResult,
  CiRefreshRejection,
  GitHubClient,
  RepoRef,
} from '@devdigest/shared';
import { WORKFLOW_VERSION } from '@devdigest/shared';
import type { AppConfig } from '../../platform/config.js';
import { NotFoundError, ValidationError, ExternalServiceError } from '../../platform/errors.js';
import { AgentsRepository, type AgentRow } from '../agents/repository.js';
import type { RepoRepository, RepoRow } from '../repos/repository.js';
import type { SkillsRepository } from '../skills/repository.js';
import { CiRepository } from './repository.js';
import {
  CI_BRANCH,
  CI_PR_TITLE,
  WORKFLOW_PATH,
  RUNNER_PATH,
  SKILLS_DIR,
  WORKFLOW_FILE,
  RESULT_ARTIFACT_NAME,
  RESULT_FILE,
  REFRESH_RUN_LIMIT,
} from './constants.js';
import { buildManifest, serializeManifest, manifestPath } from './manifest.js';
import {
  buildWorkflow,
  readWorkflowVersion,
  validateWorkflow as validateWorkflowContents,
  expectedSecrets,
} from './workflow.js';
import { readRunnerBundle } from './bundle.js';
import { uniqueSlugs, installationToDto } from './helpers.js';
import { verifyResult, type WorkflowRunFacts } from './ingest.js';

const AGENT_NOT_FOUND_MESSAGE = 'Agent not found';
const REPO_NOT_FOUND_MESSAGE = 'Repository not found';
const RUNNER_NOT_BUILT_MESSAGE =
  'The CI runner is not built. Run "cd agent-runner && pnpm install && pnpm build" and try again.';

/**
 * CiService (ring 2) — the Export-to-CI use cases: preview, workflow
 * validation, install (commit + PR + record) and listing installations.
 *
 * Deps are explicit (`onion-architecture`'s "New services take explicit
 * deps"), never a full `Container`. `CiRepository` owns only
 * `ci_installations`; the single `repos`-row lookup the install/preview
 * sequence needs (`repos.id` → `RepoRow`) goes through `RepoRepository`,
 * the same ring-3 data-access class `evals/service.ts` already consumes.
 */
export interface CiServiceDeps {
  repo: CiRepository;
  agents: AgentsRepository;
  repos: RepoRepository;
  skills: SkillsRepository;
  github: () => Promise<GitHubClient>;
  config: Pick<AppConfig, 'runnerBundlePath'>;
}

export class CiService {
  constructor(private deps: CiServiceDeps) {}

  async preview(
    workspaceId: string,
    agentId: string,
    input: CiExportInput,
  ): Promise<CiExportPreview> {
    const agent = await this.requireAgent(workspaceId, agentId);
    const repoRow = await this.requireRepo(workspaceId, input.repo_id);
    const base = input.base ?? repoRow.defaultBranch;
    const { files, workflowContents, skillCount } = await this.buildFiles(agent, input);
    return {
      files,
      workflow_version: WORKFLOW_VERSION,
      expected_secrets: expectedSecrets(workflowContents),
      repo: repoRow.fullName,
      base,
      ci_fail_on: agent.ciFailOn,
      skill_count: skillCount,
    };
  }

  validateWorkflow(_workspaceId: string, contents: string): CiWorkflowValidation {
    return validateWorkflowContents(contents);
  }

  async install(
    workspaceId: string,
    agentId: string,
    input: CiExportInput,
  ): Promise<CiExport> {
    // 1.
    const agent = await this.requireAgent(workspaceId, agentId);
    // 2.
    const repoRow = await this.requireRepo(workspaceId, input.repo_id);
    const base = input.base ?? repoRow.defaultBranch;
    // 3.
    if (input.target !== 'gha') {
      throw new ValidationError(
        `CI target "${input.target}" is not available yet — only "gha" (GitHub Actions) is supported.`,
      );
    }
    // 4 + 5 (build the files; validate/accept workflow_contents inside).
    const { files, workflowContents } = await this.buildFiles(agent, input);

    const github = await this.deps.github();
    const repoRef = { owner: repoRow.owner, name: repoRow.name };

    // 6.
    try {
      await github.commitFiles(repoRef, {
        branch: CI_BRANCH,
        base,
        message: CI_PR_TITLE,
        files: files.map((f) => ({ path: f.path, contents: f.contents })),
      });
    } catch (err) {
      throw new ExternalServiceError(
        `Failed to commit CI files to ${repoRow.fullName} (step: commit): ${(err as Error).message}`,
      );
    }

    // 7.
    let prUrl: string;
    try {
      const existing = await github.findOpenPr(repoRef, CI_BRANCH);
      if (existing) {
        prUrl = existing.url;
      } else {
        const opened = await github.openPullRequest(repoRef, {
          title: CI_PR_TITLE,
          head: CI_BRANCH,
          base,
          body: 'Adds a DevDigest CI review workflow generated by DevDigest. Review and merge to start automated PR reviews.',
        });
        prUrl = opened.url;
      }
    } catch (err) {
      throw new ExternalServiceError(
        `Failed to open the CI pull request on ${repoRow.fullName} (step: open PR): ${(err as Error).message}`,
      );
    }

    // 8. Only now — a failure above records nothing.
    const row = await this.deps.repo.upsertInstallation({
      workspaceId,
      agentId,
      repo: repoRow.fullName,
      targetType: input.target,
      workflowVersion: readWorkflowVersion(workflowContents),
      prUrl,
      ciFailOn: agent.ciFailOn,
    });

    return {
      installation: installationToDto(row, agent.name, WORKFLOW_VERSION),
      files,
      pr_url: prUrl,
    };
  }

  async listInstallations(workspaceId: string, agentId: string): Promise<CiInstallation[]> {
    const agent = await this.requireAgent(workspaceId, agentId);
    const rows = await this.deps.repo.listForAgent(workspaceId, agentId);
    return rows.map((row) => installationToDto(row, agent.name, WORKFLOW_VERSION));
  }

  async listRuns(workspaceId: string): Promise<CiRun[]> {
    return this.deps.repo.listRunsForWorkspace(workspaceId);
  }

  async listRunsForAgent(workspaceId: string, agentId: string): Promise<CiRun[]> {
    await this.requireAgent(workspaceId, agentId);
    return this.deps.repo.listRunsForAgent(workspaceId, agentId);
  }

  /**
   * AC-14, AC-15, AC-16, AC-23, AC-24 — pull the latest workflow runs for
   * every CI installation in the workspace and ingest what has finished.
   * Per installation, newest run first:
   *   1. List the workflow's runs.
   *   2. Skip runs already stored in a TERMINAL status (recorded/unavailable)
   *      — BEFORE fetching anything.
   *   3. An unfinished run → an `in_progress` row, no counts.
   *   4. Otherwise download the result artifact. `null` → an `unavailable`
   *      row (never a zero-findings row).
   *   5. `verifyResult` rejects → nothing is recorded; the rejection goes on
   *      the response instead (AC-15).
   *   6. Ok → an `agent_runs` row (`source: 'ci'`, `pr_id: null`, AC-24),
   *      then the `ci_runs` row in `recorded` status.
   */
  async refresh(workspaceId: string): Promise<CiRefreshResult> {
    const installations = await this.deps.repo.listInstallationsForWorkspace(workspaceId);
    const github = await this.deps.github();

    let recorded = 0;
    let skippedExisting = 0;
    const rejected: CiRefreshRejection[] = [];

    for (const installation of installations) {
      const repoRef = repoRefOf(installation.repo);

      // 1.
      const workflowRuns = await github.listWorkflowRuns(
        repoRef,
        WORKFLOW_FILE,
        REFRESH_RUN_LIMIT,
      );

      // 2. Skip terminal runs before fetching anything.
      const terminal = await this.deps.repo.terminalProviderRunIds(
        installation.id,
        workflowRuns.map((run) => run.id),
      );

      for (const run of workflowRuns) {
        if (terminal.has(run.id)) {
          skippedExisting++;
          continue;
        }

        // 3.
        if (!run.finished) {
          await this.deps.repo.upsertRun({
            workspaceId,
            ciInstallationId: installation.id,
            agentId: installation.agentId,
            agentRunId: null,
            providerRunId: run.id,
            prNumber: run.prNumbers[0] ?? null,
            headSha: run.headSha,
            ranAt: new Date(run.createdAt),
            status: 'in_progress',
            verdict: null,
            unavailableReason: null,
            findingsCount: null,
            criticalCount: null,
            warningCount: null,
            suggestionCount: null,
            costUsd: null,
            durationMs: null,
            githubUrl: run.htmlUrl,
            manifestVersion: null,
            model: null,
            runnerBuild: null,
          });
          continue;
        }

        // 4.
        const text = await github.downloadRunArtifactEntry(
          repoRef,
          run.id,
          RESULT_ARTIFACT_NAME,
          RESULT_FILE,
        );
        if (text === null) {
          await this.deps.repo.upsertRun({
            workspaceId,
            ciInstallationId: installation.id,
            agentId: installation.agentId,
            agentRunId: null,
            providerRunId: run.id,
            prNumber: run.prNumbers[0] ?? null,
            headSha: run.headSha,
            ranAt: new Date(run.createdAt),
            status: 'unavailable',
            verdict: null,
            unavailableReason: 'no readable result artifact for this run',
            findingsCount: null,
            criticalCount: null,
            warningCount: null,
            suggestionCount: null,
            costUsd: null,
            durationMs: null,
            githubUrl: run.htmlUrl,
            manifestVersion: null,
            model: null,
            runnerBuild: null,
          });
          continue;
        }

        // 5.
        const facts: WorkflowRunFacts = {
          repo: installation.repo,
          headSha: run.headSha,
          prNumbers: run.prNumbers,
          jobUrl: run.htmlUrl,
        };
        const verified = verifyResult(text, facts);
        if (!verified.ok) {
          rejected.push({ job_url: run.htmlUrl, reason: verified.reason });
          continue;
        }

        // 6.
        const artifact = verified.artifact;
        const agentRunId = await this.deps.repo.insertCiAgentRun({
          workspaceId,
          agentId: installation.agentId,
          provider: null,
          model: artifact.model,
          durationMs: artifact.duration_ms ?? 0,
          costUsd: artifact.cost_usd,
          findingsCount: artifact.findings_count,
          blockers: artifact.critical,
          warningCount: artifact.warning,
          suggestionCount: artifact.suggestion,
        });
        await this.deps.repo.upsertRun({
          workspaceId,
          ciInstallationId: installation.id,
          agentId: installation.agentId,
          agentRunId,
          providerRunId: run.id,
          prNumber: artifact.pr_number,
          headSha: artifact.head_sha,
          ranAt: new Date(run.createdAt),
          status: 'recorded',
          verdict: artifact.verdict,
          unavailableReason: null,
          findingsCount: artifact.findings_count,
          criticalCount: artifact.critical,
          warningCount: artifact.warning,
          suggestionCount: artifact.suggestion,
          costUsd: artifact.cost_usd,
          durationMs: artifact.duration_ms,
          githubUrl: run.htmlUrl,
          manifestVersion: artifact.manifest_version,
          model: artifact.model,
          runnerBuild: artifact.runner_build,
        });
        recorded++;
      }
    }

    return {
      runs: await this.deps.repo.listRunsForWorkspace(workspaceId),
      recorded,
      skipped_existing: skippedExisting,
      rejected,
      installations_checked: installations.length,
    };
  }

  // ---- internals -----------------------------------------------------

  private async requireAgent(workspaceId: string, agentId: string): Promise<AgentRow> {
    const agent = await this.deps.agents.getById(workspaceId, agentId);
    if (!agent) throw new NotFoundError(AGENT_NOT_FOUND_MESSAGE);
    return agent;
  }

  private async requireRepo(workspaceId: string, repoId: string): Promise<RepoRow> {
    const row = await this.deps.repos.getById(workspaceId, repoId);
    if (!row) throw new NotFoundError(REPO_NOT_FOUND_MESSAGE);
    return row;
  }

  /** Build the manifest, per-skill and runner files, plus the workflow file
   *  (generated, or the caller's own `workflow_contents` verbatim once
   *  validated — AC-22). Bundle check (AC-5) happens first: nothing is
   *  written when the runner bundle is missing. */
  private async buildFiles(
    agent: AgentRow,
    input: CiExportInput,
  ): Promise<{ files: CiFile[]; workflowContents: string; skillCount: number }> {
    const bundle = readRunnerBundle(this.deps.config.runnerBundlePath);
    if (bundle === null) {
      throw new ValidationError(RUNNER_NOT_BUILT_MESSAGE);
    }

    const linked = await this.deps.agents.linkedSkills(agent.id);
    const skillSlugs = uniqueSlugs(linked.map((l) => l.skill.name));
    const agentSlug = uniqueSlugs([agent.name])[0]!;

    const manifest = buildManifest({ agent, skillSlugs, postAs: input.post_as });
    const files: CiFile[] = [
      {
        path: manifestPath(agentSlug),
        contents: serializeManifest(manifest),
        editable: false,
      },
      ...linked.map((l, i) => ({
        path: `${SKILLS_DIR}/${skillSlugs[i]}.md`,
        contents: l.skill.body,
        editable: false,
      })),
      { path: RUNNER_PATH, contents: bundle, editable: false },
    ];

    let workflowContents: string;
    if (input.workflow_contents != null) {
      const validation = validateWorkflowContents(input.workflow_contents);
      if (!validation.valid) {
        throw new ValidationError(validation.error ?? 'Invalid workflow YAML');
      }
      workflowContents = input.workflow_contents;
    } else {
      workflowContents = buildWorkflow(input.triggers);
    }
    files.push({ path: WORKFLOW_PATH, contents: workflowContents, editable: true });

    return { files, workflowContents, skillCount: linked.length };
  }
}

/** Split a stored `"owner/name"` full name into a `RepoRef`. */
function repoRefOf(fullName: string): RepoRef {
  const [owner, name] = fullName.split('/', 2) as [string, string];
  return { owner, name };
}
