import type {
  CiExportInput,
  CiExportPreview,
  CiExport,
  CiInstallation,
  CiWorkflowValidation,
  CiFile,
  GitHubClient,
} from '@devdigest/shared';
import { WORKFLOW_VERSION } from '@devdigest/shared';
import type { AppConfig } from '../../platform/config.js';
import { NotFoundError, ValidationError, ExternalServiceError } from '../../platform/errors.js';
import { AgentsRepository, type AgentRow } from '../agents/repository.js';
import type { RepoRepository, RepoRow } from '../repos/repository.js';
import type { SkillsRepository } from '../skills/repository.js';
import { CiRepository } from './repository.js';
import { CI_BRANCH, CI_PR_TITLE, WORKFLOW_PATH, RUNNER_PATH, SKILLS_DIR } from './constants.js';
import { buildManifest, serializeManifest, manifestPath } from './manifest.js';
import {
  buildWorkflow,
  readWorkflowVersion,
  validateWorkflow as validateWorkflowContents,
  expectedSecrets,
} from './workflow.js';
import { readRunnerBundle } from './bundle.js';
import { uniqueSlugs, installationToDto } from './helpers.js';

const AGENT_NOT_FOUND_MESSAGE = 'Agent not found';
const REPO_NOT_FOUND_MESSAGE = 'Repository not found';
const RUNNER_NOT_BUILT_MESSAGE =
  'The CI runner is not built. Run "cd agent-runner && pnpm install && pnpm build" and try again.';

/**
 * CiService (ring 2) — the Export-to-CI use cases: preview, workflow
 * validation, install (commit + PR + record) and listing installations.
 *
 * Deps are explicit (`onion-architecture`'s "New services take explicit
 * deps"), never a full `Container`. `CiRepository` owns only
 * `ci_installations`; the single `repos`-row lookup the install/preview
 * sequence needs (`repos.id` → `RepoRow`) goes through `RepoRepository`,
 * the same ring-3 data-access class `evals/service.ts` already consumes.
 */
export interface CiServiceDeps {
  repo: CiRepository;
  agents: AgentsRepository;
  repos: RepoRepository;
  skills: SkillsRepository;
  github: () => Promise<GitHubClient>;
  config: Pick<AppConfig, 'runnerBundlePath'>;
}

export class CiService {
  constructor(private deps: CiServiceDeps) {}

  async preview(
    workspaceId: string,
    agentId: string,
    input: CiExportInput,
  ): Promise<CiExportPreview> {
    const agent = await this.requireAgent(workspaceId, agentId);
    const repoRow = await this.requireRepo(workspaceId, input.repo_id);
    const base = input.base ?? repoRow.defaultBranch;
    const { files, workflowContents, skillCount } = await this.buildFiles(agent, input);
    return {
      files,
      workflow_version: WORKFLOW_VERSION,
      expected_secrets: expectedSecrets(workflowContents),
      repo: repoRow.fullName,
      base,
      ci_fail_on: agent.ciFailOn,
      skill_count: skillCount,
    };
  }

  validateWorkflow(_workspaceId: string, contents: string): CiWorkflowValidation {
    return validateWorkflowContents(contents);
  }

  async install(
    workspaceId: string,
    agentId: string,
    input: CiExportInput,
  ): Promise<CiExport> {
    // 1.
    const agent = await this.requireAgent(workspaceId, agentId);
    // 2.
    const repoRow = await this.requireRepo(workspaceId, input.repo_id);
    const base = input.base ?? repoRow.defaultBranch;
    // 3.
    if (input.target !== 'gha') {
      throw new ValidationError(
        `CI target "${input.target}" is not available yet — only "gha" (GitHub Actions) is supported.`,
      );
    }
    // 4 + 5 (build the files; validate/accept workflow_contents inside).
    const { files, workflowContents } = await this.buildFiles(agent, input);

    const github = await this.deps.github();
    const repoRef = { owner: repoRow.owner, name: repoRow.name };

    // 6.
    try {
      await github.commitFiles(repoRef, {
        branch: CI_BRANCH,
        base,
        message: CI_PR_TITLE,
        files: files.map((f) => ({ path: f.path, contents: f.contents })),
      });
    } catch (err) {
      throw new ExternalServiceError(
        `Failed to commit CI files to ${repoRow.fullName} (step: commit): ${(err as Error).message}`,
      );
    }

    // 7.
    let prUrl: string;
    try {
      const existing = await github.findOpenPr(repoRef, CI_BRANCH);
      if (existing) {
        prUrl = existing.url;
      } else {
        const opened = await github.openPullRequest(repoRef, {
          title: CI_PR_TITLE,
          head: CI_BRANCH,
          base,
          body: 'Adds a DevDigest CI review workflow generated by DevDigest. Review and merge to start automated PR reviews.',
        });
        prUrl = opened.url;
      }
    } catch (err) {
      throw new ExternalServiceError(
        `Failed to open the CI pull request on ${repoRow.fullName} (step: open PR): ${(err as Error).message}`,
      );
    }

    // 8. Only now — a failure above records nothing.
    const row = await this.deps.repo.upsertInstallation({
      workspaceId,
      agentId,
      repo: repoRow.fullName,
      targetType: input.target,
      workflowVersion: readWorkflowVersion(workflowContents),
      prUrl,
      ciFailOn: agent.ciFailOn,
    });

    return {
      installation: installationToDto(row, agent.name, WORKFLOW_VERSION),
      files,
      pr_url: prUrl,
    };
  }

  async listInstallations(workspaceId: string, agentId: string): Promise<CiInstallation[]> {
    const agent = await this.requireAgent(workspaceId, agentId);
    const rows = await this.deps.repo.listForAgent(workspaceId, agentId);
    return rows.map((row) => installationToDto(row, agent.name, WORKFLOW_VERSION));
  }

  // ---- internals -----------------------------------------------------

  private async requireAgent(workspaceId: string, agentId: string): Promise<AgentRow> {
    const agent = await this.deps.agents.getById(workspaceId, agentId);
    if (!agent) throw new NotFoundError(AGENT_NOT_FOUND_MESSAGE);
    return agent;
  }

  private async requireRepo(workspaceId: string, repoId: string): Promise<RepoRow> {
    const row = await this.deps.repos.getById(workspaceId, repoId);
    if (!row) throw new NotFoundError(REPO_NOT_FOUND_MESSAGE);
    return row;
  }

  /** Build the manifest, per-skill and runner files, plus the workflow file
   *  (generated, or the caller's own `workflow_contents` verbatim once
   *  validated — AC-22). Bundle check (AC-5) happens first: nothing is
   *  written when the runner bundle is missing. */
  private async buildFiles(
    agent: AgentRow,
    input: CiExportInput,
  ): Promise<{ files: CiFile[]; workflowContents: string; skillCount: number }> {
    const bundle = readRunnerBundle(this.deps.config.runnerBundlePath);
    if (bundle === null) {
      throw new ValidationError(RUNNER_NOT_BUILT_MESSAGE);
    }

    const linked = await this.deps.agents.linkedSkills(agent.id);
    const skillSlugs = uniqueSlugs(linked.map((l) => l.skill.name));
    const agentSlug = uniqueSlugs([agent.name])[0]!;

    const manifest = buildManifest({ agent, skillSlugs, postAs: input.post_as });
    const files: CiFile[] = [
      {
        path: manifestPath(agentSlug),
        contents: serializeManifest(manifest),
        editable: false,
      },
      ...linked.map((l, i) => ({
        path: `${SKILLS_DIR}/${skillSlugs[i]}.md`,
        contents: l.skill.body,
        editable: false,
      })),
      { path: RUNNER_PATH, contents: bundle, editable: false },
    ];

    let workflowContents: string;
    if (input.workflow_contents != null) {
      const validation = validateWorkflowContents(input.workflow_contents);
      if (!validation.valid) {
        throw new ValidationError(validation.error ?? 'Invalid workflow YAML');
      }
      workflowContents = input.workflow_contents;
    } else {
      workflowContents = buildWorkflow(input.triggers);
    }
    files.push({ path: WORKFLOW_PATH, contents: workflowContents, editable: true });

    return { files, workflowContents, skillCount: linked.length };
  }
}
