import type { CSSProperties } from "react";

/** Co-located styles for ExportWizard. */
export const s = {
  body: { padding: 24, display: "flex", flexDirection: "column", gap: 18 } satisfies CSSProperties,

  stepsRow: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 4 } satisfies CSSProperties,
  stepOfLine: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,

  stepContainer: { outline: "none" } satisfies CSSProperties,

  h3: { fontSize: 14, fontWeight: 700, marginBottom: 10 } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  reasonText: { fontSize: 12.5, color: "var(--warn)", marginTop: 8 } satisfies CSSProperties,

  alert: {
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,

  // ---- Step 0: target ------------------------------------------------
  cardsGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 } satisfies CSSProperties,
  card: (selected: boolean, disabled: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
    textAlign: "left",
    padding: 14,
    minHeight: 24,
    borderRadius: 9,
    border: "1.5px solid " + (selected ? "var(--accent)" : "var(--border-strong)"),
    background: selected ? "var(--accent-bg)" : "var(--bg-elevated)",
    color: disabled ? "var(--text-muted)" : "var(--text-primary)",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.6 : 1,
  }),
  cardTitle: { fontSize: 13.5, fontWeight: 700 } satisfies CSSProperties,
  cardDesc: { fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
  cardBadge: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.03em",
    padding: "2px 7px",
    borderRadius: 5,
    border: "1px solid var(--border-strong)",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  recommendedBadge: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.03em",
    padding: "2px 7px",
    borderRadius: 5,
    background: "var(--accent)",
    color: "#fff",
  } satisfies CSSProperties,

  // ---- Step 1: preview -------------------------------------------------
  previewGrid: { display: "flex", gap: 16, minHeight: 320 } satisfies CSSProperties,
  fileList: {
    width: 220,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    borderRight: "1px solid var(--border)",
    paddingRight: 12,
  } satisfies CSSProperties,
  fileRow: (selected: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    textAlign: "left",
    padding: "7px 9px",
    minHeight: 24,
    borderRadius: 6,
    border: "none",
    background: selected ? "var(--bg-hover)" : "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
    cursor: "pointer",
  }),
  fileRowPath: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  editableTag: { fontSize: 10, fontWeight: 700, color: "var(--accent-text)", flexShrink: 0 } satisfies CSSProperties,
  contentsPane: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  contentsHeader: { display: "flex", alignItems: "center", gap: 8, fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  codeReadOnly: {
    flex: 1,
    minHeight: 260,
    resize: "vertical",
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    fontSize: 12.5,
    lineHeight: 1.55,
    fontFamily: "monospace",
    overflow: "auto",
  } satisfies CSSProperties,
  codeEditable: {
    flex: 1,
    minHeight: 260,
    resize: "vertical",
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 12.5,
    lineHeight: 1.55,
    fontFamily: "monospace",
    outline: "none",
  } satisfies CSSProperties,

  // ---- Step 2: configure ------------------------------------------------
  triggerRow: { display: "flex", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  triggerChip: (checked: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "7px 12px",
    minHeight: 24,
    borderRadius: 99,
    border: "1.5px solid " + (checked ? "var(--accent)" : "var(--border-strong)"),
    background: checked ? "var(--accent-bg)" : "var(--bg-elevated)",
    color: checked ? "var(--accent)" : "var(--text-secondary)",
    fontSize: 12.5,
    fontWeight: 600,
    cursor: "pointer",
  }),
  secretsTable: { width: "100%", borderCollapse: "collapse", fontSize: 12.5, marginTop: 4 } satisfies CSSProperties,
  secretsTh: {
    textAlign: "left",
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: "0.03em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    padding: "6px 8px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  secretsTd: { padding: "7px 8px", borderBottom: "1px solid var(--border)", color: "var(--text-primary)" } satisfies CSSProperties,
  radioRow: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  radioLabel: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, cursor: "pointer" } satisfies CSSProperties,
  note: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.5,
    padding: 10,
    borderRadius: 7,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,

  // ---- Step 3: install ------------------------------------------------
  installCards: { display: "flex", gap: 12 } satisfies CSSProperties,
  installCard: (inert: boolean): CSSProperties => ({
    flex: 1,
    padding: 14,
    borderRadius: 9,
    border: "1.5px solid " + (inert ? "var(--border)" : "var(--accent)"),
    background: inert ? "var(--bg-surface)" : "var(--accent-bg)",
    opacity: inert ? 0.6 : 1,
  }),
  installCardTitle: { fontSize: 13.5, fontWeight: 700, marginBottom: 4 } satisfies CSSProperties,
  installCardBody: { fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  successBox: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 16,
    borderRadius: 9,
    border: "1px solid var(--ok)",
    background: "var(--ok-bg)",
  } satisfies CSSProperties,
  successTitle: { fontSize: 14, fontWeight: 700, color: "var(--ok)" } satisfies CSSProperties,
  prLink: { fontSize: 13, color: "var(--accent-text)", wordBreak: "break-all" } satisfies CSSProperties,

  footer: { display: "flex", alignItems: "center", gap: 10, justifyContent: "flex-end" } satisfies CSSProperties,
} as const;
