import type { CSSProperties } from "react";

export const s = {
  box: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  quote: {
    margin: 0,
    fontSize: 14,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  divider: {
    border: "none",
    borderTop: "1px solid var(--border)",
    margin: "14px 0",
  } satisfies CSSProperties,
  scopeBlock: {} satisfies CSSProperties,
  scopeLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  scopeList: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 13.5,
    color: "var(--text-secondary)",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  emptyState: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: "14px 16px",
  } satisfies CSSProperties,
  emptyMessage: {
    fontSize: 13.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  derivingState: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: "14px 16px",
    fontSize: 13.5,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,

  // ---- RISK AREAS subsection (mockups 3-5) --------------------------------
  risksEmpty: {
    fontSize: 13.5,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  risksList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  riskRow: {
    borderTop: "1px solid var(--border)",
    padding: "10px 0",
  } satisfies CSSProperties,
  riskHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
  } satisfies CSSProperties,
  riskSeverity: (color: string, bg: string): CSSProperties => ({
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.03em",
    color,
    background: bg,
    borderRadius: 4,
    padding: "2px 7px",
    marginTop: 1,
  }),
  riskMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  riskTitle: {
    display: "block",
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  riskRefs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 3,
  } satisfies CSSProperties,
  riskRefButton: {
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 12.5,
    color: "var(--sugg)",
    cursor: "pointer",
  } satisfies CSSProperties,
  riskExpandButton: {
    flexShrink: 0,
    background: "none",
    border: "none",
    padding: 4,
    cursor: "pointer",
    color: "var(--text-muted)",
    display: "flex",
    minWidth: 24,
    minHeight: 24,
    alignItems: "center",
    justifyContent: "center",
  } satisfies CSSProperties,
  riskChevron: (expanded: boolean): CSSProperties => ({
    transform: expanded ? "rotate(180deg)" : "none",
    transition: "transform .12s",
  }),
  riskExplanation: {
    margin: "8px 0 0",
    paddingLeft: 62,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  recalculateRow: {
    marginTop: 8,
    display: "flex",
    justifyContent: "flex-start",
  } satisfies CSSProperties,
} as const;
