import type { CSSProperties } from "react";

/** Co-located styles for ContextAttachPanel (agent/skill Context tabs). */
export const s = {
  wrap: { padding: "24px 28px 40px", maxWidth: 960 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 17, fontWeight: 700 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 220,
    marginLeft: "auto",
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-secondary)", marginBottom: 16, lineHeight: 1.5 } satisfies CSSProperties,
  overBudget: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    marginBottom: 14,
    borderRadius: 7,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg, rgba(230,160,40,0.1))",
    color: "var(--warn)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,

  row: (attached: boolean, isOver: boolean, isDragging: boolean, missing: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    minHeight: 24,
    padding: "10px 14px",
    borderRadius: 8,
    cursor: missing ? "default" : "pointer",
    border:
      "1px solid " + (isOver ? "var(--accent)" : attached ? "var(--border-strong)" : "var(--border)"),
    background: attached ? "var(--bg-elevated)" : "transparent",
    opacity: isDragging ? 0.45 : 1,
  }),
  grip: (draggable: boolean): CSSProperties => ({
    minWidth: 24,
    minHeight: 24,
    display: "grid",
    placeItems: "center",
    color: draggable ? "var(--text-muted)" : "var(--border-strong)",
    cursor: draggable ? "grab" : "not-allowed",
    flexShrink: 0,
    // Button reset — the grip is a real <button> (A2), not a styled <span>,
    // so the UA's default border/background/padding must be zeroed out to
    // keep the rendered row identical to mockups 02/03.
    background: "none",
    border: "none",
    padding: 0,
  }),
  checkbox: (on: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    borderRadius: 4,
    flexShrink: 0,
    border: "1.5px solid " + (on ? "var(--accent)" : "var(--border-strong)"),
    background: on ? "var(--accent)" : "transparent",
    display: "grid",
    placeItems: "center",
  }),
  checkIcon: { color: "#fff" } satisfies CSSProperties,
  name: {
    fontSize: 13,
    fontWeight: 600,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  folderBadge: {
    fontSize: 11,
    color: "var(--text-secondary)",
    flexShrink: 0,
  } satisfies CSSProperties,
  tokenCount: { fontSize: 11.5, color: "var(--text-secondary)", flexShrink: 0 } satisfies CSSProperties,
  missingBadge: { fontSize: 11, color: "var(--crit)", flexShrink: 0 } satisfies CSSProperties,
  previewBtn: {
    minWidth: 24,
    minHeight: 24,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 11.5,
    flexShrink: 0,
    cursor: "pointer",
  } satisfies CSSProperties,
  preview: {
    margin: "0 0 8px 40px",
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12.5,
    maxHeight: 260,
    overflow: "auto",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 18,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  footerTokens: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  footerNote: { marginLeft: "auto", fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
} as const;
