import type { CSSProperties } from "react";

/** Co-located styles for EvalsTab. */
export const s = {
  wrap: { padding: 24, display: "flex", flexDirection: "column", gap: 28 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10 } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  h3: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 10,
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  // A single visually-hidden live region carrying the run control's own
  // progress text (AC-60) — clipped rather than `display: none`, so screen
  // readers still announce it.
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0,0,0,0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: 10,
  } satisfies CSSProperties,
  metricCard: {
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  metricLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  metricValue: { fontSize: 22, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  passingCount: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginTop: 10,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowMain: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  rowInfo: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  nameRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  name: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  location: { fontSize: 12, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  statusRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-secondary)",
    marginTop: 2,
  } satisfies CSSProperties,
  badge: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowActions: { display: "flex", gap: 4, flexShrink: 0 } satisfies CSSProperties,
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  editForm: { display: "flex", gap: 8, alignItems: "center" } satisfies CSSProperties,
  fragmentList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  fragmentItem: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  fragmentHead: { display: "flex", alignItems: "baseline", gap: 8 } satisfies CSSProperties,
  fragmentTitle: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  fragmentSeverity: {
    fontSize: 11,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  fragmentMeta: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
} as const;
